# Generated by Django 6.0 on 2026-01-02 13:10

import docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docs/')),
                ('qr', models.ImageField(blank=True, upload_to='qr/')),
                ('guid', models.CharField(default=docs.models.guid_generator, editable=False, max_length=40, unique=True)),
                ('pin', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
