# Generated by Django 6.0 on 2026-03-09 16:42

import docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docs/')),
                ('source_file', models.FileField(blank=True, editable=False, upload_to='docs/source/')),
                ('qr', models.ImageField(blank=True, upload_to='qr/')),
                ('qr_page', models.IntegerField(default=1)),
                ('guid', models.CharField(default=docs.models.guid_generator, editable=False, max_length=40, unique=True)),
                ('pin', models.CharField(default=docs.models.generate_pin, max_length=4)),
                ('qr_x', models.FloatField(default=0.78)),
                ('qr_y', models.FloatField(default=0.78)),
                ('qr_scale', models.FloatField(default=0.14)),
                ('pin_x', models.FloatField(default=0.68)),
                ('pin_y', models.FloatField(default=0.92)),
                ('pin_font_size', models.FloatField(default=22.5)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
