# Generated by Django 6.0 on 2026-01-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='have_qr',
            field=models.BooleanField(default=True),
        ),
    ]
