# Generated by Django 6.0 on 2026-01-06 05:54

import docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_document_have_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pin',
            field=models.CharField(default=docs.models.generate_pin, max_length=4),
        ),
    ]
