# Generated by Django 6.0 on 2026-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_document_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='have_qr',
        ),
        migrations.AddField(
            model_name='document',
            name='pin_font_size',
            field=models.FloatField(default=22.5),
        ),
        migrations.AddField(
            model_name='document',
            name='pin_x',
            field=models.FloatField(default=0.68),
        ),
        migrations.AddField(
            model_name='document',
            name='pin_y',
            field=models.FloatField(default=0.92),
        ),
        migrations.AddField(
            model_name='document',
            name='qr_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='qr_scale',
            field=models.FloatField(default=0.14),
        ),
        migrations.AddField(
            model_name='document',
            name='qr_x',
            field=models.FloatField(default=0.78),
        ),
        migrations.AddField(
            model_name='document',
            name='qr_y',
            field=models.FloatField(default=0.78),
        ),
        migrations.AddField(
            model_name='document',
            name='source_file',
            field=models.FileField(blank=True, editable=False, upload_to='docs/source/'),
        ),
    ]
